### PR TITLE
Build static binaries in release jobs

### PR DESCRIPTION
**Pull request by adaszko**

### CODE REVIEW

**Comment by adaszko** [comment]
> Nice. Surprised you got this working! Can you swap the commit order so we don't have any failure?

Thanks :)  The commits are now swapped.

**Review by cloudhead — DISMISSED** [review]

**Comment by xphoniex** [comment]
It's no longer necessary to freeze rust version on 1.59.0 since https://github.com/radicle-dev/radicle-cli/commit/f987ba3253d40f95b8b5e3f13ae371fc09ae3402 got merged, please omit https://github.com/radicle-dev/radicle-cli/pull/74/commits/648e8312b64058f3d5df23fb8bb1a0b8335d5069 .

**Comment by cloudhead** [comment]
> It's no longer necessary to freeze rust version on 1.59.0 since [f987ba3](https://github.com/radicle-dev/radicle-cli/commit/f987ba3253d40f95b8b5e3f13ae371fc09ae3402) got merged, please omit [648e831](https://github.com/radicle-dev/radicle-cli/commit/648e8312b64058f3d5df23fb8bb1a0b8335d5069) .

It is though, as this will happen again and again.

**Comment by adaszko** [comment]
Thanks for merging 👍 

> It's no longer necessary to freeze rust version on 1.59.0 since [f987ba3](https://github.com/radicle-dev/radicle-cli/commit/f987ba3253d40f95b8b5e3f13ae371fc09ae3402) got merged, please omit [648e831](https://github.com/radicle-dev/radicle-cli/commit/648e8312b64058f3d5df23fb8bb1a0b8335d5069) .

It's an instance of a more general problem: Clippy keeps on introducing new lints with each release.  If we are always on latest stable in CI, we get CI failures that are completely unrelated to the changes introduced in some given PR, just because clippy has automatically been upgraded under the hood.  That's counterproductive.  An opt-in kind of process of upgrading Clippy is going to work better.

**Pull request merged**
